### PR TITLE
Improve figures

### PR DESCRIPTION
**Pull request by jeremymoreau**

### CODE REVIEW

**Comment by mschoettle** [comment]
Nice! I really like the line chart with the 7-day avg line over it. It would actually be really cool to use this in more places. For example for new cases/deaths. I'm not sure if the total numbers are really helpful in those (I find it makes it harder to see the daily new numbers). Maybe they could be put into the hover label or not shown (the current total is/will be in the mini boxes on top anyway)?

Here are some comments:

* the labels should indicate that the 7-day rolling average is shown
* I find the hospitalizations figure too crowded. What do you think of separating it into two? Or moving some data into the hover label?
* the test positivity still is rounded, not sure why
* for the test positivity, does it make sense to use the average? I would either use the actual rate or put it into the hover label/add the actual rate as a line chart

**Comment by jeremymoreau** [comment]
Thanks!

I did actually add the 7-day rolling average to cases and deaths plots already. I also added a secondary y-axis so that it's easier to see both cumulative case counts and new cases at the same time (same as for the hospitalisation fig).
cases

I agree that the hospitalisation plot is a bit crowded (mainly because of the legend). I'm thinking of just putting it in one of the x2 rows, and putting a simpler plot in its place in that x3 row (maybe Rt or vaccinations). Also, this is unfortunately not a very discoverable feature, but you can double click on any label in the legend to isolate the trace (or single click to hide it).

And good idea, I will add that it is a 7-day average in the labels. Also yes, the test positivity is still rounded to the nearest unit in the hover label, I will change that. I had also rounded the actual data, but reverted it since it doesn't make sense for percentages. I do think the 7-day rolling average makes sense for test positivity as well since it's a fairly noisy metric (the day-to-day variability is probably partially artefactual). JHU also reports a rolling average for test positivity: https://coronavirus.jhu.edu/testing/individual-states
test positivity

**Comment by jeremymoreau** [comment]
Added a new vaccination fig. I will probably switch the "new doses" to a 7-day rolling average once we have more data. Otherwise, I think this is ready to merge for now. Next thing on my list is adding the new mini boxes (my holidays end on Monday, so that might be the last big addition I make for a while!). I think the new mini boxes, updated map showing incidence, and perhaps a figure showing Rt trends are the major things left?

vaccination

**Comment by mschoettle** [comment]
Great work! Thanks for adding doing the whole vaccination data and figure as well.

For the labels where the 7-day avg is shown I would mention it next to the number (I think called the hover template?) and also show the actual new number. But it's not that important, I can take care of little things later.

Yes, I think so. I have some more ideas for figures (7-day rolling avg of new cases per borough, 7-day rolling avg of new cases per QC region + QC).

**Comment by jeremymoreau** [comment]
Sounds good! I put the "(7-day moving average)" text in the y-axis because it takes up a lot of space, but maybe we could add something shorter in the hovertemplate (e.g. 7-day avg/moy. 7 jours) like you suggest.

**Pull request merged**
