### PR TITLE
Add new info in mini boxes and arrange MTL/QC into separate rows

### PR DESCRIPTION
**Pull request by jeremymoreau**
I've added everything discussed in #55 except for Rt since we haven't added that data yet (and also don't have a source for the MTL Rt yet). I don't think we should add any more mini boxes than this though as space for text is already limited and making the font any smaller (or adding line-breaks) wouldn't look nice. So for Rt, we could have it only in a figure or replace one of the mini boxes. I'd favour only having it in a figure since we need to add some explanations as to which values are forecasted vs. actual estimates.

Some screenshots (laptop, iPad, mobile):
127 0 0 1_8050_en(Laptop with HiDPI screen)

### CODE REVIEW

**Comment by mschoettle** [comment]
This is really great, I really like it. Great work.

I agree with just showing the Rt figure. I am still not so sure how helpful Rt is anyway since it lags behind (as far as I understand). I'm fine with leaving it at showing the current info. This gives a good overview and anything else can be shown in the figures.

Regarding the layout, would it be possible to show 4/3 in the following cases?

Screen Shot 2021-01-02 at 13 32 58
Screen Shot 2021-01-02 at 13 33 23

Maybe it's just decreasing the lower breaking point but I can give you window sizes if you need.
I guess for the iPhone screenshot you showed there is no way to squeeze it to 3 per row.

Some comments:
* Does the colouring of the mini boxes have any meaning?
* The hosp. and ICU are still at 0 for me, I think they might lag behind by a day. For QC we could use the data from `data_qc_hosp` maybe? The same applies to test positivity actually. Maybe we need to specify that somehow that it is not from the same date (although I don't see any space to do so).
* I noticed that the case and death numbers are not those reported on that day (hosp. and ICU I cannot tell but could be the same). I think this is due to some of them attributed to past dates. I'd be in favor of showing all new numbers. To do that, we would have to save those numbers from `data_qc.csv`. QC numbers are actually available in `data_qc_manual_data.csv` but unfortunately it lacks MTL and there is no equivalent.
* For the 7-day incidence, if I tested it right this morning, the last 7 day sum is not the same as the rolling 7 day sum from 7 days ago. I'm fine with either but it could be easily done with `df['new_cases'].rolling('7d').sum()[-7]` and the CSV might have to be loaded with `parse_dates=True` so that the date is a date index.

**Comment by jeremymoreau** [comment]
Thanks!

- I added a new 3*4 layout for browser widths between 1400px and 1000px. I set 6x2 for widths under 700px, which covers most smartphones (the media query is based on the viewport dimensions, not the actual number of pixels). Three columns doesn't fit even on big phones unfortunately (I use the Chrome device inspector for this):
iphone


- The colours are mostly just because I think it looks prettier (and they make it easier to see which data are the same for MTL/QC). The (admittedly rather arbitrary) reasoning for the colours: red = bad (new cases), black triage tags = deceased (deaths), code orange = external disaster/mass casualty (hospitalisations), code blue = medical emergency/cardiac arrest (ICU). Might be nice to automatically switch "test positivity" to green if it drops below 5% (which is the cutoff most sources seem to suggest for a "good"/"bad" rule of thumb). Without colours:
nocolour

- For hospitalisations, you're right, the data seems to lag behind by a day. It also doesn't seem as useful since it's only the new admissions without taking into account the discharges. I think what I will do for now is change the label to "yesterday", e.g. "+53 yesterday" for hospitalisations and "-0.5% yesterday" for test positivity. Not perfect, but at least it indicates that those data lag behind the other by a day. I like the data in `data_qc_hosp` better too since it shows the nb of active cases, but I think it might be confusing to show different data for MTL and QC, so maybe let's just have that in the figure for now (unless the INSPQ starts publishing those data by region as well).
- The nb of cases/deaths is always for the previous day (i.e. on 2020-12-31, the nb of new cases is for 2020-12-30 since cases for 2020-12-31 are incomplete/still being counted). Not sure I'm understanding you correctly, but you're right that the numbers for QC in `data_qc_manual_data.csv` appear to be slightly more up to date. I'm ok with displaying those numbers for QC instead. It would be slightly inconsistent with the MTL numbers but more accurate. The numbers reported on the Santé Montréal website are also different (slightly more out of date?).
- For the 7-day incidence: I think it is actually the same thing (but it's the rolling sum for -8 days so that there's no overlap). I just used the index because it was less confusing in my head.
    -  Last 7 days:
        -  `data_mtl['new_cases'].dropna().iloc[-7:].sum() == data_mtl['new_cases'].rolling(7).sum().iloc[-1]`
    - The 7 days before that:
        -  `data_mtl['new_cases'].dropna().iloc[-14:-7].sum() == data_mtl['new_cases'].rolling(7).sum().iloc[-8]`

**Comment by mschoettle** [comment]
Thanks!

* the sizing is great now
* the colours make sense to me, thanks for the explanation. I agree that it would be nice to colour the percent positivity (WHO recommends < 5 %). We could also use the colours from the 7-day incidence map to colour the 7-day incidences in the mini boxes :)
* hospitalisations: I agree that it's best to keep it the same for both. QC also has current numbers on [quebec.ca/coronavirus](https://www.quebec.ca/en/health/health-issues/a-z/2019-coronavirus/situation-coronavirus-in-quebec/) but still nothing for MTL. I will bug Sante Montreal again. I was thinking a bit about it and maybe from a psychological perspective it's better to just show new admissions as you show now. For COVID-19 patients stay in the hospital longer so the discharged patients could have been in there for a while. Only showing the difference (active hosp.) might not show the current trend then.
* hospitalisations again: I just looked at it again and I found it a bit odd to have + ICU and + total. I'd find it better to have ICU and regular instead of the total. And to show the change from the day before (if that makes sense, basically to show a trend), but there might not be enough space for that.
* number of cases/deaths/(hosp?): if you look at the following table from the above mentioned quebec.ca URL you can see that for Dec 30th (the last date we currently have) that there are 2819 new cases, 44 deaths (originally it was reported as 62 deaths on that day, not sure why this is changed now. It was reported as "62 more deaths, 22 of which occurred in the last 24 hours").

Screen Shot 2021-01-03 at 14 17 07 1

You can also observe this if you take the very last row of `data_qc.csv` (in `sources/2020-12-30`) and compare it with the last row of the same in `sources/2020-12-29/`). I believe they adjust the numbers for past dates.

Since the MTL data is also coming out of the same file we could use the same approach. Basically whenever there is new data we would have to save it and then use those for the mini boxes (or just the comparison). If you want I could add something to `refreshdata.py`.

And you're right about the 7-day incidence calculation. My bad.

**Comment by mschoettle** [comment]
Btw: Interesting today with the new data (which is unfortunately only available on quebec.ca). The QC vaccines administered total is lower than on Dec 30th:

Screen Shot 2021-01-03 at 16 27 13

Screen Shot 2021-01-03 at 16 32 37

**Comment by jeremymoreau** [comment]
- Great idea about changing the 7-day incidence values to match the map!! I've implemented that and changing the test positivity rate colour when it drops under 5%.
- Agreed about hospitalisations. Looking at the hospitalisations figure again, it seems like new hospitalisations might actually be the better metric in any case since active hospitalisation numbers lag behind (which makes sense).
- I've switched the hospitalisations mini boxes to show new regular admissions (instead of total) and new ICU admissions. About the trend, maybe if we had one box for each of regular/ICU admissions, but I'm currently using the superscript space for ICU admissions (also not sure how to explain that it's a difference of a difference in such a small space). The trend info is in the figure, so I think it's fine to leave this as is.
- Sounds good about the data from quebec.ca, yes please do what you think is best thanks! I agree that in general we should try to display the latest numbers (from whichever source tends to stay most up-to-date) for the info in the mini boxes. The figures can show slightly less up-to-date, but more consistent data. They adjust numbers for past dates as new counts come in (and sometimes correct cases attributed to the wrong date). Like a lot of things in hospitals, I believe much of these data are still being reported with paper forms (often faxed) so there will be delays/inaccuracies. e.g. this form: https://publications.msss.gouv.qc.ca/msss/fichiers/2020/20-210-103W.pdf

**Comment by mschoettle** [comment]
Awesome, thanks! I really like the new mini boxes. One thing that would still be nice is the 7-day avg of new cases/deaths/hosp but I'll think about how this could be squeezed in there. I will take care of the data, tracking it in #60.

> also not sure how to explain that it's a difference of a difference in such a small space

We could make use of tooltips on hover (example: https://getbootstrap.com/docs/4.5/components/tooltips/) but it would require a bit of CSS (and JS) to do that.

**Comment by jeremymoreau** [comment]
This is a nice library for (very easy) pure CSS tooltips: https://kazzkiq.github.io/balloon.css/

You'd need to use this special syntax for the HTML attributes that Dash doesn't support natively:
```python
**{'aria-label': 'This is a tooltip!', 'data-balloon-pos': 'up'}
```

**Pull request merged**
