### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mschoettle**
Updates the all dependencies to the latest version. I unpinned (not sure what it is called) `pandas` and `dash`. Not sure if there was a reason for doing this but the latest versions seem to work.

Also added a travis CI config. @jeremymoreau as the owner/admin would have to add the integration to it, if you are interested to activate it.

### CODE REVIEW

**Comment by jeremymoreau** [comment]
@mschoettle I've never used Travis CI, but I think I've added the integration. Let me know if there are any issues.

**Comment by jeremymoreau** [comment]
Actually it looks like Travis-ci just updated their pricing and now are requiring us to send an application for free open source credits: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

Any way to achieve what you were looking to do with the Free (for public repos) GitHub Actions? Or circle-ci?

My inclination would be to use Github actions since it's free and built-in (e.g. https://github.com/marketplace/actions/flake8-action). What do you think @mschoettle ?

**Comment by mschoettle** [comment]
Wouldn't the free plan (which you should have by default) be enough?

Anyway, it doesn't matter to me which service it is. The problem with GitHub actions I see is that it is not using the same environment (as far as I can tell) which could potentially miss some problems. But might be enough. There are some actions that support both flake8 and mypy.

**Comment by jeremymoreau** [comment]
Seems like they've eliminated their free plan as of last month unfortunately (replaced with a one-time trial credit for ~1000 minutes of run time).

**Comment by mschoettle** [comment]
I see. I might have missed that since for some reason I am still on an education plan.

**Pull request merged**
