### PR TITLE
Adds data updater script for daily automatic updates.

### LINKED ISSUE #37: Schedule refreshdata.py to run daily and deploy changes automatically
Once the missing data are added and `refreshdata.py` is able to update all the data sources without any manual intervention, it'd be nice to have it run automatically daily without any user input.

Since the Dokku server has no persistent storage (it is overwritten on every new deploy), I was thinking we could maybe use github actions to do this (e.g. using https://jasonet.co/posts/scheduled-actions/). We'd setup a `schedule` event to run `refreshdata.py` daily and commit the updated data files back to the repo.

I've set up a workflow that will automatically deploy the `deploy` branch to the Dokku server (https://github.com/jeremymoreau/covid19mtl/blob/master/.github/workflows/main.yml)

### PR DESCRIPTION
**Pull request by mschoettle**
Partially fixes #37.

One known problem is if the `<date>.0` tag already exists.

I currently scheduled to run this script every day at 13:00 (the INSPQ data is updated around noon, for Santé Montreal I am still waiting to see when they actually update their website, looks like the next time will be Monday).

### CODE REVIEW

**Comment by mschoettle** [comment]
INSPQ will not update from Dec 25th to 27th, so the next update will also be on Monday

**Comment by mschoettle** [comment]
Nice! Thanks for adding the version tag part.

> Also changed how $YESTERDAY was defined because it wasn't working on my mac (maybe a different version of bash?)

Yeah, there seems to be a difference between `date` on Mac and `date` on Linux. Since I run it on my Raspberry Pi (based on Debian) I used the compatible command for that.

I added an if/else block to support both.

**Comment by jeremymoreau** [comment]
Sounds good! Did you use the script for the 4e861f637126fa88ca42f4be2b524d8e3063cd76 update? It seems like no tag was added so I was wondering if it worked ok.

**Comment by mschoettle** [comment]
That was by accident. I wanted to look at it before pushing but I accidentally only commented out the `git push --tags` and not the first push as well.

So it seems to work. One thing I noticed in that commit though (unfortunately even though QC released data for the weekend, it was only available on quebec.ca not from INSPQ) is that the change in `data_mtl_death_loc.csv` includes the same numbers from the previous day (Dec 23) because it wasn't updated. There are actually quite a few rows in this CSV where the numbers did not change from one day to the next. Do you think that should be detected and replaced with 'na'?

**Comment by mschoettle** [comment]
Worked well this afternoon at 13:00. INSPQ and Sante Montreal had their data updated at that time (usually around noon, I added a safety buffer). I added functions to check the data date (https://github.com/jeremymoreau/covid19mtl/tree/determine-data-date) which we could use to ensure new data is shown. To handle INSPQ and Sante Mtl differently it would require some work though.

**Comment by jeremymoreau** [comment]
Sounds good to me! Yes, I agree that it'd probably be best to add NAs when the data don't change, but it's probably not terrible to leave it as is for now (also how would we know when the case numbers actually do not change later on when daily counts have slowed down?). Feel free to merge this if you think it's ready.

**Comment by mschoettle** [comment]
Thanks! True, I started preparing something to determine the actual date of the data (see #34).

**Pull request merged**
